### ISSUE TITLE
sio.loadmat('.../slide_window_processed/')

### ISSUE THREAD

**Issue by asice5** [Zzzsdu/DAST#1]
你好，我想请问data_process.py文件中的trainX = sio.loadmat('.../slide_window_processed/')运行报错，这个mat文件是哪一个呢

**Comment by BIGDUCKGAGAGA** [comment]
你好，想问下你解决了吗，我也遇到这个问题了

**Comment by asice5** [comment]
你好，我是直接把这个注释掉了，直接使用上面的trainX



发自我的iPhone


------------------ Original ------------------
From: BIGDUCKGAGAGA ***@***.***&gt;
Date: Sun,May 1,2022 9:58 AM
To: Zzzsdu/DAST ***@***.***&gt;
Cc: asice5 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Zzzsdu/DAST] sio.loadmat('.../slide_window_processed/') (Issue#1)

**Comment by BIGDUCKGAGAGA** [comment]
yzw已收到您的邮件！

**Comment by BIGDUCKGAGAGA** [comment]
已收到您的回复，问题已解决，谢谢您！

**Comment by Zzzsdu** [comment]
> 

Represents the mat processed by the sliding time window

**Comment by asice5** [comment]
> > 
> 
> Represents the mat processed by the sliding time window

thanks

**Comment by LoneFireBlossom** [comment]
> 你好，我是直接把这个注释掉了，直接使用上面的trainX 发自我的iPhone
> […](#)

注释掉的话会报错

> ValueError: cannot reshape array of size 6692400 into shape (16731,40,14,1)

请问应该怎么办呀😭急需😭

**Comment by BIGDUCKGAGAGA** [comment]
yzw已收到您的邮件！

**Comment by BIGDUCKGAGAGA** [comment]
yzw已收到您的邮件！
